# Reward configuration for Luigi Bros environment
# All reward values used during training

explorer:
  # Basic rewards
  alive_bonus: 0.1
  new_ground_multiplier: 2.0
  new_ground_base: 0.1
  
  # Movement rewards
  forward_multiplier: 0.08
  backward_penalty: -0.15
  standing_still_penalty: -0.1
  standing_still_threshold: 0.1
  
  # Jump rewards
  jump_proximity_max_reward: 2.0
  jump_proximity_max_distance: 3  # in tiles
  
  # Block rewards
  question_block_reward: 15.0
  mushroom_block_reward: 25.0
  
  # Coin rewards
  coin_reward: 5.0

speedrunner:
  # Basic rewards
  new_ground_multiplier: 3.0
  new_ground_base: 0.1
  
  # Movement rewards
  forward_multiplier: 0.25
  backward_penalty: -0.15
  standing_still_penalty: -0.15
  standing_still_threshold: 0.1
  
  # Time penalty
  time_penalty: -0.005
